services:
  nginx:
    build:
      context: ./nginx/dev
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev/config/nginx:/etc/nginx
      - ./nginx/dev/share/index.html:/usr/share/nginx/html/index.html
    restart: on-failure:5
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - guaradata-backend

  ghost_mysql:
    image: mysql:8.0
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_USER_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - guaradata-backend

  ghost:
    image: ghost:5-alpine
    restart: always
    env_file: .env
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      - database__client=${DATABASE_CLIENT}
      - database__connection__host=${DATABASE_HOST}
      - database__connection__user=${DATABASE_USER}
      - database__connection__password=${DATABASE_PASSWORD}
      - database__connection__database=${DATABASE_NAME}
      # this url value is just an example, and is likely wrong for your environment!
      - url=${GHOST_URL}
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
    volumes:
      - ghost:/var/lib/ghost/content
    networks:
      - guaradata-backend
    depends_on:
    - ghost_mysql

  mysql_backup:
    image: mysql:8.0
    profiles: ["backup"]
    entrypoint: ["sh", "-c"]
    command: >
      "mysqldump --no-tablespaces -h ghost_mysql -u ${DATABASE_USER} -p${DATABASE_USER_PASSWORD} ${DATABASE_NAME} > /backups/backup.sql"
    volumes:
      - ./mysql_backups:/backups
    depends_on:
      - ghost_mysql
    networks:
      - guaradata-backend
    env_file: .env
  
  guaradata_portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - guaradata-backend

volumes:
  ghost:
  db:
  portainer_data:

networks:
  guaradata-backend:
    driver: bridge
  default:
    external: true