services:
  nginx:
    build:
      context: ./nginx/prod
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/prod/config/nginx:/etc/nginx
      - ./nginx/prod/share/index.html:/usr/share/nginx/html/index.html
      - /etc/letsencrypt:/etc/letsencrypt
    restart: on-failure:5
    networks:
      - guaradata-backend

  ghost:
    image: ghost:5-alpine
    restart: always
    env_file: .env
    environment:
      - database__client=${DATABASE_CLIENT}
      - database__connection__host=${DATABASE_HOST}
      - database__connection__user=${DATABASE_USER}
      - database__connection__password=${DATABASE_PASSWORD}
      - database__connection__database=${DATABASE_NAME}
      - url=${GHOST_URL}
      - mail__transport=${MAIL_TRANSPORT}
      - mail__options__from=${MAIL_FROM}
      - mail__options__service=${MAIL_SERVICE}
      - mail__options__secure=${MAIL_SECURE}
      - mail__options__host=${MAIL_HOST}
      - mail__options__port=${MAIL_PORT}
      - mail__options__auth__user=${MAIL_AUTH_USER}
      - mail__options__auth__pass=${MAIL_AUTH_PASS}
    volumes:
      - ghost:/var/lib/ghost/content
    networks:
      - guaradata-backend

  ghost_mysql:
    image: mysql:8.0
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_USER_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    volumes:
      - db:/var/lib/mysql
      - ./mysql_backups:/backups
    networks:
      - guaradata-backend

  nuxt_guaradata:
    image: ivbpinheiro/guaradata:latest
    restart: always
    env_file: .env
    environment:
      - NUXT_PUBLIC_GHOST_API_BASE=${NUXT_PUBLIC_GHOST_API_BASE}
      - NUXT_PUBLIC_GHOST_API_KEY=${NUXT_PUBLIC_GHOST_API_KEY}
      - NUXT_PUBLIC_GHOST_API_VERSION=${NUXT_PUBLIC_GHOST_API_VERSION}
    networks:
      - guaradata-backend

  mysql_backup:
    image: mysql:8.0
    profiles: ["backup"]
    entrypoint: ["sh", "-c"]
    command: >
      "mysqldump -h ghost_mysql -u ${DATABASE_USER} -p${DATABASE_USER_PASSWORD} ${DATABASE_NAME} > /backups/backup.sql"
    volumes:
      - ./mysql_backups:/backups
    depends_on:
      - ghost_mysql
    networks:
      - guaradata-backend
    env_file: .env
  
  guaradata_portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - guaradata-backend

volumes:
  ghost:
  db:
  portainer_data:

networks:
  guaradata-backend:
    driver: bridge
  default:
    external: true
