services:
  nginx:
    build:
      context: ./nginx/prod
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/prod/config/nginx:/etc/nginx
      - ./nginx/prod/share/index.html:/usr/share/nginx/html/index.html
      - /etc/letsencrypt:/etc/letsencrypt
    restart: on-failure:5
    networks:
      - guaradata-backend

  ghost:
    image: ghost:5.119.2-alpine
    restart: always
    env_file: .env
    environment:
      - database__client=${DATABASE_CLIENT}
      - database__connection__host=${DATABASE_HOST}
      - database__connection__user=${DATABASE_USER}
      - database__connection__password=${DATABASE_PASSWORD}
      - database__connection__database=${DATABASE_NAME}
      - url=${GHOST_URL}
    volumes:
      - ghost:/var/lib/ghost/content
    networks:
      - guaradata-backend

  ghost_mysql:
    image: mysql:8.0
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_USER_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    volumes:
      - db:/var/lib/mysql
    networks:
      - guaradata-backend

  nuxt-guaradata:
    image: ivbpinheiro/guaradata:latest
    restart: always
    env_file: .env
    environment:
      - NUXT_PUBLIC_GHOST_API_BASE=${NUXT_PUBLIC_GHOST_API_BASE}
      - NUXT_PUBLIC_GHOST_API_KEY=${NUXT_PUBLIC_GHOST_API_KEY}
      - NUXT_PUBLIC_GHOST_API_VERSION=${NUXT_PUBLIC_GHOST_API_VERSION}
    networks:
      - guaradata-backend

volumes:
  ghost:
  db:

networks:
  guaradata-backend:
    driver: bridge
  default:
    external: true
