name: Executar outra ação quando frontend não for alterado

on:
  push:
    branches:
      - main

jobs:
  check-frontend-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Verificar mudanças na pasta frontend
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'

  deploy-to-aws:
    needs: check-frontend-changes
    if: needs.check-frontend-changes.outputs.frontend_changed == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy na AWS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd guaradata-frontend-ghost-cms
            git pull origin main
            sudo docker compose -f docker-compose.prod.yaml down
            sudo docker compose -f docker-compose.prod.yaml pull
            sudo docker compose -f docker-compose.prod.yaml up --force-recreate --build -d